#!/bin/bash

#PBS -N timeseries
#PBS -q geyser
#PBS -l select=1:ncpus=16:mpiprocs=16
#PBS -l walltime=04:00:00
#PBS -A None

source /etc/profile.d/modules.sh

export MPI_UNBUFFERED_STDIO=true
export TMPDIR=$TMPDIR


##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########

if [ ! -e /Users/jnicklas1/cesmppp/CESM_postprocessing/cesm-env2/bin ]; then
    echo "*************************************************************************************"
    echo "CESM timeseries exiting due to non-existant python virtual environment in"
    echo "    /Users/jnicklas1/cesmppp/CESM_postprocessing/cesm-env2/bin"
    echo "You must first run:"
    echo "$POSTPROCESS_PATH/create_python_env -machine [machine]"
    echo "*************************************************************************************"
    exit
fi





## activate the virtualenv that contains all the non-bootstrapped dependencies

cd /Users/jnicklas1/cesmppp/CESM_postprocessing/cesm-env2/bin
echo "Running from virtualenv directory:"
echo $pwd
cd ..
eval "$(conda shell.bash hook)"
conda activate $(pwd)
cd bin
## load the boot-strap modules 





## The PYTHONPATH setting here is for libraries that are not available via modules.
PYTHONPATH=/Users/jnicklas1/miniforge3/envs/cesm-env0/lib/python3.12:$PYTHONPATH
export PYTHONPATH


today="$(date '+%Y%m%d-%H%M%S')"
log_filename=/Volumes/lawrencedata/cesm1/b.scontrol1/postprocess/logs/timeseries.log.$today


mpirun -n 36 --oversubscribe ./cesm_tseries_generator.py --debug 2  --caseroot /Volumes/lawrencedata/cesm1/b.scontrol1/postprocess >> ${log_filename} 2>&1

